interface ingredientOptions {
  value: string;
  label: string;
}

export const ingredientOptions = [
      { value: 'Tomate', label: '🍅 Tomate' },
      { value: 'Cebola', label: '🧅 Cebola' },
      { value: 'Alho', label: '🧄 Alho' },
      { value: 'Batata', label: '🥔 Batata' },
      { value: 'Cenoura', label: '🥕 Cenoura' },
      { value: 'Brócolis', label: '🥦 Brócolis' },
      { value: 'Alface', label: '🥬 Alface' },
      { value: 'Espinafre', label: '🌿 Espinafre' },
      { value: 'Pepino', label: '🥒 Pepino' },
      { value: 'Pimentão', label: '🫑 Pimentão' },
      { value: 'Chuchu', label: '🥒 Chuchu' },
      { value: 'Nabo', label: '🥕 Nabo' },
      { value: 'Couve-flor', label: '🌽 Couve-flor' },
      { value: 'Almeirão', label: '🥬 Almeirão' },
      { value: 'Rúcula', label: '🥬 Rúcula' },
      { value: 'Couve', label: '🥬 Couve' },
      { value: 'Hortelã', label: '🌿 Hortelã' },
      { value: 'Salsão', label: '🌿 Salsão' },
      { value: 'Couve-de-Bruxelas', label: '🌿 Couve-de-Bruxelas' },
      { value: 'Acelga', label: '🌿 Acelga' },
      { value: 'Maçã', label: '🍎 Maçã' },
      { value: 'Banana', label: '🍌 Banana' },
      { value: 'Laranja', label: '🍊 Laranja' },
      { value: 'Manga', label: '🥭 Manga' },
      { value: 'Uva', label: '🍇 Uva' },
      { value: 'Abacaxi', label: '🍍 Abacaxi' },
      { value: 'Morangos', label: '🍓 Morangos' },
      { value: 'Melancia', label: '🍉 Melancia' },
      { value: 'Peras', label: '🍐 Peras' },
      { value: 'Kiwi', label: '🥝 Kiwi' },
      { value: 'Coco', label: '🥥 Coco' },
      { value: 'Figo', label: '🍑 Figo' },
      { value: 'Tâmara', label: '🌴 Tâmara' },
      { value: 'Lichia', label: '🥭 Lichia' },
      { value: 'Frango', label: '🐔 Frango' },
      { value: 'Carne', label: '🥩 Carne' },
      { value: 'Peixe', label: '🐟 Peixe' },
      { value: 'Presunto', label: '🍖 Presunto' },
      { value: 'Bacon', label: '🥓 Bacon' },
      { value: 'Salsicha', label: '🌭 Salsicha' },
      { value: 'Frutos do Mar', label: '🦐 Frutos do Mar' },
      { value: 'Tofu', label: '🍽️ Tofu' },
      { value: 'Queijo', label: '🧀 Queijo' },
      { value: 'Leite', label: '🥛 Leite' },
      { value: 'Manteiga', label: '🧈 Manteiga' },
      { value: 'Requeijão', label: '🧀 Requeijão' },
      { value: 'Creme de Leite', label: '🥛 Creme de Leite' },
      { value: 'Queijo ralado', label: '🧀 Queijo ralado' },
      { value: 'Gorgonzola', label: '🧀 Gorgonzola' },
      { value: 'Parmigiano', label: '🧀 Parmigiano' },
      { value: 'Ricota', label: '🧀 Ricota' },
      { value: 'Iogurte', label: '🥛 Iogurte' },
      { value: 'Creme Azedo', label: '🥛 Creme Azedo' },
      { value: 'Creme de Leite Fresco', label: '🥛 Creme de Leite Fresco' },
      { value: 'Ricota Fresca', label: '🧀 Ricota Fresca' },
      { value: 'Arroz', label: '🍚 Arroz' },
      { value: 'Macarrão', label: '🍝 Macarrão' },
      { value: 'Feijão', label: '🍲 Feijão' },
      { value: 'Lentilha', label: '🥣 Lentilha' },
      { value: 'Grão-de-bico', label: '🍲 Grão-de-bico' },
      { value: 'Farinha', label: '🌾 Farinha' },
      { value: 'Levedura', label: '🍞 Levedura' },
      { value: 'Manteiga de Amendoim', label: '🥜 Manteiga de Amendoim' },
      { value: 'Sal', label: '🧂 Sal' },
      { value: 'Pimenta', label: '🌶️ Pimenta' },
      { value: 'Alecrim', label: '🌿 Alecrim' },
      { value: 'Orégano', label: '🌿 Orégano' },
      { value: 'Salsinha', label: '🌿 Salsinha' },
      { value: 'Cebolinha', label: '🌱 Cebolinha' },
      { value: 'Louro', label: '🌿 Louro' },
      { value: 'Gengibre', label: '🫚 Gengibre' },
      { value: 'Canela', label: '🌰 Canela' },
      { value: 'Curry', label: '🌶️ Curry' },
      { value: 'Mostarda', label: '🌭 Mostarda' },
      { value: 'Maionese', label: '🍔 Maionese' },
      { value: 'Ketchup', label: '🍔 Ketchup' },
      { value: 'Páprica', label: '🌶️ Páprica' },
      { value: 'Pimenta-do-reino', label: '🌶️ Pimenta-do-reino' },
      { value: 'Especiarias', label: '🌶️ Especiarias' },
      { value: 'Cerveja', label: '🍺 Cerveja' },
      { value: 'Vinho', label: '🍷 Vinho' },
      { value: 'Soya', label: '🍶 Soya' },
      { value: 'Café', label: '☕ Café' },
      { value: 'Chá', label: '🍵 Chá' },
      { value: 'Chocolate', label: '🍫 Chocolate' },
      { value: 'Mel', label: '🍯 Mel' },
      { value: 'Azeite', label: '🫒 Azeite' },
      { value: 'Vinagre', label: '🍇 Vinagre' },
      { value: 'Pipoca', label: '🍿 Pipoca' },
      { value: 'Gelatina', label: '🍧 Gelatina' },
      { value: 'Creme de Leite', label: '🥛 Creme de Leite' },
      { value: 'Soro de Leite', label: '🥛 Soro de Leite' },
      { value: 'Sorvete', label: '🍨 Sorvete' },
      { value: 'Caldo', label: '🍲 Caldo' },
      { value: 'Alcaparras', label: '🫒 Alcaparras' },
      { value: 'Azeitonas', label: '🫒 Azeitonas' },
      { value: 'Picles', label: '🥒 Picles' },
];

export const utensilOptions = [
  { value: 'Airfryer', label: 'Airfryer' },
  { value: 'Forno', label: 'Forno' },
  { value: 'Fogão', label: 'Fogão' },
  { value: 'Micro-ondas', label: 'Micro-ondas' },
];